version: "3"
services:
  transmission:
    image: transmission
    build: .
    volumes:
      - ./settings.json:/etc/transmission-daemon/settings.json
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
